# Generated by Django 6.0.6 on 2026-06-28 16:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField(unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Project Sequence',
                'verbose_name_plural': 'Project Sequences',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(editable=False, help_text='Automatically generated project code.', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Official project title.', max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='Automatically generated URL slug.', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the research project.')),
                ('objectives', models.TextField(blank=True, help_text='Research objectives.')),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated keywords for searching and classification.')),
                ('funding_agency', models.CharField(blank=True, help_text='Funding organization supporting the project.', max_length=255)),
                ('grant_number', models.CharField(blank=True, help_text='Official grant or award number.', max_length=100)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, help_text='Approved project budget.', max_digits=15, null=True)),
                ('ethics_approval_number', models.CharField(blank=True, help_text='Ethics approval reference number.', max_length=100)),
                ('start_date', models.DateField(blank=True, db_index=True, null=True)),
                ('end_date', models.DateField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='DRAFT', help_text='Current lifecycle status of the project.', max_length=20)),
                ('visibility', models.CharField(choices=[('PRIVATE', 'Private'), ('ORGANIZATION', 'Organization'), ('PUBLIC', 'Public')], default='PRIVATE', help_text='Controls who can view this project.', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether the project is active.')),
                ('organization', models.ForeignKey(help_text='Organization that owns this project.', on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='organizations.organization')),
                ('owner', models.ForeignKey(help_text='User who created and owns the project.', on_delete=django.db.models.deletion.PROTECT, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
                ('principal_investigator', models.ForeignKey(blank=True, help_text='Principal Investigator for the project.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='principal_investigator_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='projects_pr_status_f023cb_idx'), models.Index(fields=['visibility'], name='projects_pr_visibil_b48d7f_idx'), models.Index(fields=['organization'], name='projects_pr_organiz_da3a59_idx')],
            },
        ),
    ]
