# Generated by Django 6.0.6 on 2026-06-28 17:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('PRINCIPAL_INVESTIGATOR', 'Principal Investigator'), ('PROJECT_MANAGER', 'Project Manager'), ('DATA_MANAGER', 'Data Manager'), ('RESEARCHER', 'Researcher'), ('ENUMERATOR', 'Enumerator'), ('ANALYST', 'Data Analyst'), ('VIEWER', 'Viewer')], default='RESEARCHER', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_invitations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['project', 'user'],
                'constraints': [models.UniqueConstraint(fields=('project', 'user'), name='unique_project_member'), models.CheckConstraint(condition=models.Q(('role__isnull', False)), name='project_member_role_not_null')],
            },
        ),
    ]
