# Generated by Django 6.0.6 on 2026-06-27 23:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bio', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('timezone', models.CharField(blank=True, max_length=100)),
                ('preferred_language', models.CharField(default='en', max_length=20)),
                ('website', models.URLField(blank=True)),
                ('profile_visibility', models.CharField(choices=[('public', 'Public'), ('organization', 'Organization'), ('private', 'Private')], default='public', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['user__email'],
            },
        ),
        migrations.CreateModel(
            name='ResearcherProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('faculty', models.CharField(blank=True, max_length=255)),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('highest_degree', models.CharField(blank=True, max_length=100)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('research_interests', models.TextField(blank=True)),
                ('orcid', models.CharField(blank=True, max_length=50)),
                ('google_scholar', models.URLField(blank=True)),
                ('researchgate', models.URLField(blank=True)),
                ('scopus_author_id', models.CharField(blank=True, max_length=100)),
                ('web_of_science_id', models.CharField(blank=True, max_length=100)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='researcher_profile', to='profiles.userprofile')),
            ],
            options={
                'verbose_name': 'Researcher Profile',
                'verbose_name_plural': 'Researcher Profiles',
                'ordering': ['profile__user__email'],
            },
        ),
    ]
